regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    activations: Tanh
    attention_excluded_regions: []
    attention_excluded_regions_dict: {}
    attention_excluded_regions_sampling: {}
    batch_size: 8
    cls_from_all_to_cls: False
    cls_from_cls_to_all: False
    combine_inputs: True
    dropout: 0.15
    embedding_learning_rate: null
    encoder_learning_rate: 1.0e-05
    encoder_model: PrefixRoBERTa
    hidden_sizes:
      - 3072
      - 1024
    input_segments:
      - hyp
      - src
      - ref
    keep_embeddings_frozen: True
    layer: mix
    layerwise_decay: 0.95
    learning_rate: 3.0e-05
    multiple_segment_embedding: False
    nr_frozen_epochs: 0.01
    optimizer: AdamW
    pool: cls
    pretrained_model: 'roberta-large'
    reset_position_for_each_segment: False
    training_data_path: {'sum_doc': 'data/train/Document_matching_oriented_data.jsonl', 'sum_ref': 'data/train/Summary_matching_oriented_data.jsonl'}
    validation_data_path: data/test/SummEval.jsonl

 
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml